### PR TITLE
feat: support multiple GraphQL operations

### PR DESCRIPTION
**Pull request by bag-man**
This is adds support for GraphQL queries with multiple operations.

It has some errors when dealing with the error bounds and when you access the details for a query with multiple operations. Unfortunately, I can't figure those out, I'm not a front end person. 

It does appear to work on the test cases I have seen listed so far. @s12v let me know what changes are needed, so this can be merged.

### CODE REVIEW

**Comment by bag-man** [comment]
@s12v Will you be able to take a look at this?

**Comment by s12v** [comment]
@bag-man, thank you for the PR! I'll take a look this week

**Comment by bag-man** [comment]
Any luck @s12v I think it could use a lot more tweaks to make it nice, but as it is it's a lot more useful, just not quite perfect.

**Comment by bag-man** [comment]
@s12v Any thoughts? After using this more I realise it is more of a hack, but could be the basis of what to be done to make it support multiple operations properly.

**Comment by s12v** [comment]
Superseded by the v1.0.0 rewrite, which lists batched requests one row per operation (`lib/har.js`). Thanks for the PR and for the analysis in #2 — it was the reference for the batch handling.

(AI-generated)

**Pull request closed without merging**
